# Generated by Django 3.2.7 on 2022-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=100)),
                ('bred_for', models.CharField(max_length=100)),
                ('life_span', models.CharField(max_length=100)),
                ('temprament', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
